### ISSUE TITLE
Cannot set property 'parentContext' of undefined

### ISSUE THREAD

**Issue by Dante-101** [Lucifier129/react-lite#110]
I am getting this error with `react-lite`. The app works fine with `react` and `react-dom`. Any suggestions what could be wrong?
```
Uncaught (in promise) TypeError: Cannot set property 'parentContext' of undefined
    at initVcomponent (react-lite.common.js:433)
    at initVnode (react-lite.common.js:52)
    at initVcomponent (react-lite.common.js:442)
    at initVnode (react-lite.common.js:52)
    at initVchildren (react-lite.common.js:190)
    at initVelem (react-lite.common.js:173)
    at initVnode (react-lite.common.js:49)
    at initVchildren (react-lite.common.js:190)
    at initVelem (react-lite.common.js:173)
    at initVnode (react-lite.common.js:49)
```

**Comment by Lucifier129** [comment]
Try breakpoint at [this line](https://github.com/Lucifier129/react-lite/blob/master/dist/react-lite.common.js#L424), and check whether `vcomponent.type` is valid or not.

**Comment by Dante-101** [comment]
vcomponent.type is valid. It is set to a component of this external package - https://github.com/Pomax/react-onclickoutside

Here is the debug session [screenshot](https://goo.gl/photos/cQkyQhFBkSYHDKi79)

**Comment by Lucifier129** [comment]
OK. Can you add a simple code example to reproduce this problem?

**Comment by ChieveiT** [comment]
I got the same exception a few days ago and I fixed it after adding "key" prop for <Row> and <Col> of antd. Maybe you can check whether there are some elements created by the same component and having the same parent but do not have "key" prop. "react-lite just follow the best practice of React."XD

**Comment by Lucifier129** [comment]
@ChieveiT Great!

**Comment by drcmda** [comment]
@Lucifier129 
I have the same problem, it persisted for months, checked back today and still the same. Is there anything we can do to help it or at least is there an explanation of what's wrong?

**Comment by Lucifier129** [comment]
@drcmda It seems like the constructor of super class was not invoked, so `this.$cache` is `undefined`, read `parentContext` property of `undefined` would throw error.

**Comment by hskww** [comment]
i has the same error:
Uncaught TypeError: Cannot set property 'parentContext' of undefined
    at initVcomponent (react-lite.common.js:433)

beside,this page use react-router,and other pages(no router) work sucessfully

**Comment by Bbooth4** [comment]
I have gotten the same error verbatim. The likely difference in my setup from others is that I am using electron. I am uncertain if this would impact react-lite in anyway?

Has a solution been reached for this issue or simply an explanation?
